---
inherit_from:
  - nix/pure/rubocop/config/disable.yml
  - nix/pure/rubocop/config/limits.yml
  - nix/pure/rubocop/config/meta_specs.yml
  - nix/pure/rubocop/config/sandi_metz.yml
  - nix/pure/rubocop/config/style.yml
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  UseCache: true
  SuggestExtensions: true
  EnabledByDefault: true
  ActiveSupportExtensionsEnabled: true
  TargetRubyVersion: 3.4.7

plugins:
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-performance
  - rubocop-thread_safety
  - rubocop-rubycw
