# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.7'

# RSpec
# keep-sorted start
gem 'cuprite', '~> 0.17', require: false
gem 'factory_bot', '~> 6.5', require: false
gem 'mini_portile2', '~> 2.8.2', require: false
gem 'rspec', '~> 3.13.2', require: false
gem 'simplecov', '~> 0.22.0', require: false
# keep-sorted end
