# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.4.7'

# Guard
# keep-sorted start
gem 'guard-rspec', '~> 4.7', require: false
gem 'guard-rubocop', '~> 1.5', require: false
# keep-sorted end
